import json
from pathlib import Path
BASE = Path(__file__).parent
OPS = {
'point_to_point_route':'PLAN_ROUTE', 'multimodal_route':'PLAN_MULTIMODAL_ROUTE',
'route_stop_sequence':'LIST_ROUTE_STOPS', 'route_stop_membership':'CHECK_STOP_ON_ROUTE',
'first_and_last_service':'GET_FIRST_LAST_SERVICE', 'service_frequency':'GET_SERVICE_FREQUENCY',
'scheduled_departure':'GET_SCHEDULED_DEPARTURES', 'mode_availability':'CHECK_SERVICE_AVAILABILITY',
'fare_calculation':'CALCULATE_FARE', 'ticketing_and_passes':'GET_TICKETING_POLICY',
'station_facilities':'GET_STATION_FACILITY', 'station_accessibility':'GET_ACCESSIBILITY_INFO',
'interchange_transfer':'GET_INTERCHANGE_DETAILS', 'nearest_transport':'FIND_NEAREST_STATION',
'realtime_status_query':'REJECT_UNSUPPORTED_REALTIME', 'out_of_scope':'REJECT_OUT_OF_SCOPE',
}
cases=[]
def add(intent, query, test_type, behavior, slots=None, guard=False):
    cases.append(dict(id=f'HI200_{len(cases)+1:03d}', query=query, expected_intent=intent,
                      expected_operation=None if guard else OPS.get(intent), expected_slots=slots or {},
                      test_type=test_type, expected_behavior=behavior))
# All utterances and expectations below are independently authored before inference.
i='point_to_point_route'
add(i,'सैदापेट से नंदनम तक मेट्रो पकड़कर पहुँचने का रास्ता समझा दीजिए।','native_places','Plan a directionally valid metro journey; give only published route evidence.',{'transport_mode':'metro'})
add(i,'ब्रॉडवे से अडयार बस में जाना है; कहाँ चढ़ूँ, कहाँ उतरूँ?','colloquial','Recognize a bus journey request and preserve both endpoints; clarify unresolved locations.',{'transport_mode':'bus'})
add(i,'चेन्नई बीच से तिरुवान्मियूर एमआरटीएस लेकर कैसे पहुँचूँ?','mode_qualified','Route using MRTS only, or state that a published directional route is unavailable.',{'transport_mode':'mrts'})
add(i,'गिंडी से चेन्नई हवाई अड्डे तक मेट्रो वाला रास्ता बताइए, जल्दी में हूँ।','native_wording','Recognize metro journey planning, without inventing optimized travel time.',{'transport_mode':'metro'})
add(i,'अन्ना नगर से कोयम्बेडु जाने का सीधा बस मार्ग चाहिए।','direct_preference','Preserve direct bus preference; state any optimization/data limit rather than inventing a connection.',{'transport_mode':'bus','preference':'direct_only'})
add(i,'ताम्बरम से चेन्नई बीच उपनगरीय रेल में सफर कैसे करूँ?','native_mode_name','Recognize suburban rail journey planning; do not substitute metro routes.',{'transport_mode':'suburban_rail'})
add(i,'एग्मोर से वडपलनी पहुँचने की राह बता दो, भैया।','colloquial','Recognize an open point-to-point journey; preserve endpoints without choosing an arbitrary station.')
add(i,'मुझे मेट्रो से आलंदूर पहुँचना है।','missing_origin','Ask where the journey starts, without fabricating an origin.',{'transport_mode':'metro'},guard=True)
add(i,'मेट्रो में गिंडी से निकलूँगा; आगे कैसे जाऊँ?','missing_destination','Ask for destination; do not make up the intended destination.',{'transport_mode':'metro'},guard=True)
add(i,'ब्रॉडवे से मरीना बीच तक कम से कम खर्च वाले सार्वजनिक रास्ते की जानकारी चाहिए।','optimization','Recognize journey planning with cheapest preference; disclose unsupported optimization.',{'preference':'cheapest'})
add(i,'सेंट्रल से हवाई अड्डा: मेट्रो से पहुँचने का मार्ग, कृपया!','punctuation','Treat colon/comma as punctuation; preserve metro and both endpoints.',{'transport_mode':'metro'})
add(i,'गिंडी से नंदनम मेट्रो से पहुँचने का रास्ता चाहिए, किराया नहीं पूछ रहा।','negated_goal','Answer only route planning; negated fare is not a second goal.',{'transport_mode':'metro'})
i='multimodal_route'
add(i,'ताम्बरम से अन्ना नगर तक पहले लोकल रेल, फिर मेट्रो लेकर पूरा सफर कैसे बनेगा?','explicit_mode_sequence','Recognize cross-mode planning; refuse unsupported cross-mode graph rather than presenting a single-mode plan.')
add(i,'कोयम्बेडु से तिरुवान्मियूर जाना है, बस और मेट्रो मिलाकर रास्ता बनाइए।','mixed_modes','Use multimodal family and disclose missing verified transfer graph.')
add(i,'अडयार से हवाई अड्डे के लिए बस से मेट्रो जोड़कर यात्रा सुझा दो।','native_places','Recognize a combined bus-plus-metro itinerary; state source limitation.')
add(i,'चेन्नई बीच से वडपलनी रेल बदलकर मेट्रो पकड़ूँ तो पूरा मार्ग क्या होगा?','colloquial','Recognize a full mixed-mode itinerary rather than only station interchange information.')
add(i,'पेरम्बूर से गिंडी तक लोकल ट्रेन और बस दोनों का उपयोग करके पहुँचाना है।','mode_pair','Keep the combined suburban rail and bus journey goal; no fabricated transfer routing.')
add(i,'मरीना बीच से कोयम्बेडु तक एमआरटीएस और बस की जोड़ वाली यात्रा बताइए।','native_mode_wording','Classify combined MRTS/bus planning and state verified graph limitation.')
add(i,'ब्रॉडवे से शोलिंगनल्लूर तक बस-मेट्रो-बस में कहाँ-कहाँ बदलूँ?','three_leg_sequence','Recognize multi-leg multimodal route planning; do not invent transfer points.')
add(i,'गिंडी से चेन्नई बीच तक बस के बाद उपनगरीय रेल वाली योजना चाहिए।','ordered_modes','Retain bus-then-suburban-rail journey intent and source limits.')
add(i,'सेंट्रल से आईआईटी मद्रास तक मेट्रो और बस जोड़कर पूरा रास्ता समझाओ।','landmark_destination','Recognize mixed-mode route to a landmark; clarify unresolved landmark or disclose routing limitation.')
add(i,'अन्ना नगर से ताम्बरम पहुँचने में मेट्रो के साथ लोकल ट्रेन भी जोड़ सकते हैं; यात्रा बनाइए।','permissive_mixed_mode','Recognize explicit combined itinerary request, not yes/no mode availability.')
add(i,'बस और मेट्रो मिलाकर गिंडी पहुँचना है, रास्ता कहाँ से शुरू करूँ यह अभी नहीं बताया।','missing_origin','Ask for origin or explicitly disclose absent verified multimodal graph; never invent an origin.',guard=True)
add(i,'कोयम्बेडु से एमआरटीएस जोड़कर बस में आगे जाना है; अभी मंजिल तय नहीं है।','missing_destination','Ask destination or disclose absent cross-mode graph; no invented itinerary.',guard=True)
i='route_stop_sequence'
add(i,'बस रूट २१जी के शुरू से आखिर तक सारे पड़ाव क्रम में लिखिए।','devanagari_route','List published ordered stops for full route code 21G; never drop suffix.',{'route_number':'21G','transport_mode':'bus'})
add(i,'१०२ए बस किन-किन ठहरावों से होकर निकलती है? पूरी सूची चाहिए।','devanagari_suffix','Recognize complete stop sequence request for 102A, not one-stop membership.',{'route_number':'102A','transport_mode':'bus'})
add(i,'रूट ५७० में पहला पड़ाव कौन सा है और उसके बाद सारे पड़ाव किस क्रम में आते हैं?','first_stop_contrast','Recognize stop ordering rather than first service departure.',{'route_number':'570'})
add(i,'नीली लाइन के स्टेशनों का सिलसिला बताइए।','native_line','List published Blue Line station sequence, or state missing published sequence.',{'line_name':'Blue Line'})
add(i,'हरी मेट्रो लाइन पर एक स्टेशन के बाद कौन सा स्टेशन पड़ता है, पूरा क्रम बताओ।','native_line','Recognize Green Line station sequence.',{'line_name':'Green Line','transport_mode':'metro'})
add(i,'बस नंबर २७डी के रास्ते के सभी स्टॉप दिखाइए; सिर्फ आखिरी स्टॉप नहीं।','negation','List the whole 27D sequence; do not mistake last-stop wording for last service.',{'route_number':'27D','transport_mode':'bus'})
add(i,'मुझे १०२ के पड़ावों की सूची चाहिए, १०२ए की नहीं।','negated_route','Honor only route 102; negated 102A is not an additional execution scope.',{'route_number':'102'})
add(i,'रूट ४७ए — रुकने की जगहें एक-एक करके, कृपया।','punctuation','Recognize ordered stops for 47A and preserve suffix.',{'route_number':'47A'})
add(i,'एमआरटीएस लाइन के सभी स्टेशन यात्रा के क्रम में बता सकते हो?','mrts_sequence','List a published MRTS sequence or give an explicit data limit.',{'line_name':'MRTS','transport_mode':'mrts'})
add(i,'इस बस के पूरे रास्ते के पड़ाव बता दो।','missing_route','Ask route number or line; do not guess this bus.',guard=True)
add(i,'बस रूट २१ जी कहाँ-कहाँ रुकता है? सूची बनाओ।','spaced_suffix','Normalize २१ जी to route 21G without losing suffix.',{'route_number':'21G','transport_mode':'bus'})
add(i,'१०२के# बस के हर पड़ाव का क्रम देखना है।','route_variant','Preserve complete operational variant 102K# and list its own sequence.',{'route_number':'102K#','transport_mode':'bus'})
i='route_stop_membership'
add(i,'क्या २१जी बस सैदापेट के स्टॉप पर ठहरती है?','devanagari_route','Check a particular stop on route 21G using published sequence, not plan a journey.',{'route_number':'21G','transport_mode':'bus'})
add(i,'१०२ए में अडयार वाला पड़ाव शामिल है या नहीं?','membership_wording','Check membership for route 102A; do not infer absent service from incomplete coverage.',{'route_number':'102A'})
add(i,'गिंडी मेट्रो स्टेशन नीली लाइन में आता है क्या?','native_line','Check Guindy metro membership of Blue Line, without turning it into journey planning.',{'line_name':'Blue Line','transport_mode':'metro'})
add(i,'एग्मोर हरी लाइन का स्टेशन है? सिर्फ हाँ या नहीं की पुष्टि चाहिए।','yes_no','Check Green Line station membership using evidence.',{'line_name':'Green Line'})
add(i,'बस ५७० से शोलिंगनल्लूर पर उतर सकते हैं, यह स्टॉप उस रूट पर है?','colloquial','Recognize one-stop route membership for 570.',{'route_number':'570','transport_mode':'bus'})
add(i,'रूट २७डी वडपलनी में नहीं रुकता क्या?','negative_question','Answer stop membership honestly; negative question must not imply a negative fact.',{'route_number':'27D'})
add(i,'तिरुवान्मियूर एमआरटीएस लाइन के स्टेशनों में गिना जाता है?','native_membership','Check named MRTS station membership.',{'line_name':'MRTS','transport_mode':'mrts'})
add(i,'१०२के# में कन्नगी नगर वाला ठहराव है या किसी दूसरी बस में?','route_suffix','Check complete route variant 102K# and named stop, preserving suffix.',{'route_number':'102K#'})
add(i,'४७ए बस अन्ना नगर पर रुकती है; इसकी पुष्टि कर दो।','assertion_confirmation','Treat assertion with confirmation request as membership, not an established fact.',{'route_number':'47A','transport_mode':'bus'})
add(i,'इस रूट में ताम्बरम वाला स्टॉप आता है क्या?','missing_route','Ask route number or line; do not guess the referenced route.',guard=True)
add(i,'२१जी पर यह जगह पड़ती है क्या?','missing_stop','Ask which stop/location; do not fabricate one.',{'route_number':'21G'},guard=True)
add(i,'१०२ बस अडयार पर रुकती है? किराया नहीं चाहिए।','negated_fare','Handle membership only; ignored negated fare mention must not trigger multi-goal clarification.',{'route_number':'102','transport_mode':'bus'})
i='first_and_last_service'
add(i,'गिंडी मेट्रो से दिन की सबसे पहली गाड़ी कब निकलती है?','native_first','Return a published first-service time with source limits, or explicit missing schedule.',{'transport_mode':'metro','timing_type':'first'})
add(i,'वडपलनी मेट्रो की आखिरी रात वाली सेवा कितने बजे छूटती है?','native_last','Recognize last service, not live status; disclose schedule coverage limits.',{'transport_mode':'metro','timing_type':'last'})
add(i,'ताम्बरम से चेन्नई बीच जाने वाली लोकल रेल का पहला फेरा बताइए।','native_first','Preserve suburban direction and first-service goal.',{'transport_mode':'suburban_rail','timing_type':'first'})
add(i,'ब्रॉडवे से २१जी बस की अंतिम रवाना होने की घड़ी क्या है?','native_last','Use bus route 21G and boarding stop for published last service.',{'route_number':'21G','transport_mode':'bus','timing_type':'last'})
add(i,'सेंट्रल मेट्रो पर पहली और आखिरी ट्रेन का समय एक साथ चाहिए।','combined_extrema','First and last are one timing goal, not multiple unrelated goals.',{'transport_mode':'metro'})
add(i,'नीली लाइन की हवाई अड्डा मेट्रो से सुबह सबसे पहले निकलने वाली सेवा बताओ।','line_and_station','Recognize first departure from Airport on Blue Line.',{'line_name':'Blue Line','transport_mode':'metro','timing_type':'first'})
add(i,'आलंदूर से अंतिम मेट्रो कब मिलती है, देर हो जाए तो जानना है।','colloquial_last','Recognize last scheduled metro service; no live availability claim.',{'transport_mode':'metro','timing_type':'last'})
add(i,'चेन्नई बीच स्टेशन से एमआरटीएस की दिन की शुरुआती ट्रेन का वक्त चाहिए।','native_mode','Use MRTS first-service goal; state any absence of published timetable.',{'transport_mode':'mrts','timing_type':'first'})
add(i,'बस रूट ५७० का गिंडी से आखिरी फेरा किस समय छूटता है?','route_and_stop','Keep specific bus route and boarding stop, avoiding route stop sequence confusion.',{'route_number':'570','transport_mode':'bus','timing_type':'last'})
add(i,'पहली बस का समय बता दो।','missing_boarding_stop','Ask boarding stop/station and enough service context; do not guess.',{'transport_mode':'bus','timing_type':'first'},guard=True)
add(i,'ताम्बरम से रविवार की आखिरी उपनगरीय रेल कब रवाना होती है?','date_scope','Use explicit Sunday service scope if supported; otherwise explain date/calendar limitation.',{'transport_mode':'suburban_rail','timing_type':'last'})
add(i,'गिंडी मेट्रो की आखिरी ट्रेन बताइए, उसके आखिरी स्टेशन की सूची नहीं।','last_service_contrast','Answer last departure goal only; negated stop list is not another request.',{'transport_mode':'metro','timing_type':'last'})
i='service_frequency'
add(i,'गिंडी मेट्रो पर नीली लाइन की दो गाड़ियों के बीच कितना अंतर रहता है?','native_headway','Recognize route-specific scheduled headway; no live frequency claim.',{'transport_mode':'metro','line_name':'Blue Line','timing_type':'frequency'})
add(i,'ब्रॉडवे से २१जी बस कितनी-कितनी देर में मिलती है?','colloquial_headway','Use published route-specific bus departures for headway or disclose insufficiency.',{'route_number':'21G','transport_mode':'bus','timing_type':'frequency'})
add(i,'ताम्बरम से चेन्नई बीच की दक्षिण लाइन पर लोकल रेल कितनी नियमित आती है?','native_frequency','Recognize frequency for South Line with direction, not first/last.',{'transport_mode':'suburban_rail','line_name':'South Line'})
add(i,'हरी मेट्रो लाइन में एग्मोर से अगली गाड़ी के लिए आम तौर पर कितने मिनट रुकना पड़ता है?','typical_wait','Interpret typical interval as scheduled frequency, not live next-arrival.',{'transport_mode':'metro','line_name':'Green Line'})
add(i,'रूट ५७० की गिंडी से बसों का औसत अंतराल बताइए।','native_statistic','Return schedule-based headway only when directional departures support it.',{'route_number':'570','transport_mode':'bus','timing_type':'frequency'})
add(i,'वडपलनी पर हरी लाइन की मेट्रो का फेरा कितनी देर बाद दोहराता है?','native_wording','Recognize Green Line service frequency at Vadapalani.',{'line_name':'Green Line','transport_mode':'metro'})
add(i,'सैदापेट से २७डी बस का अंतराल क्या रहता है?','route_headway','Recognize bus headway using complete 27D route code.',{'route_number':'27D','transport_mode':'bus','timing_type':'frequency'})
add(i,'चेन्नई बीच पर एमआरटीएस गाड़ियाँ एक घंटे में लगभग कितनी बार आती हैं?','rate_wording','Frequency goal; disclose provisional schedule and no guessed hourly counts.',{'line_name':'MRTS','transport_mode':'mrts'})
add(i,'गिंडी मेट्रो की नीली लाइन सुबह के व्यस्त समय में कितनी देर-देर में चलती है?','peak_scope','Recognize peak headway request and preserve requested period or state scope limitation.',{'transport_mode':'metro','line_name':'Blue Line'})
add(i,'बसों के बीच कितना अंतर रहता है?','missing_route_stop','Ask which boarding stop and route/line, not arbitrary general frequency.',{'transport_mode':'bus','timing_type':'frequency'},guard=True)
add(i,'नीली लाइन की मेट्रो कितनी-कितनी देर में आती है?','missing_station','Ask station/boarding location if needed for a directional estimate.',{'line_name':'Blue Line','transport_mode':'metro'},guard=True)
add(i,'२१जी बस की ब्रॉडवे पर आवृत्ति चाहिए; पहली बस का समय मत बताना।','negated_first','Recognize frequency only; negated first-service phrase must not create another goal.',{'route_number':'21G','transport_mode':'bus','timing_type':'frequency'})
i='scheduled_departure'
add(i,'गिंडी मेट्रो से सुबह ७:१५ के बाद रवाना होने वाली गाड़ियों की समय-सारणी दिखाओ।','devanagari_clock','Normalize 07:15 and return only published departures after requested time.',{'transport_mode':'metro','time':'07:15:00','timing_type':'departure'})
add(i,'ब्रॉडवे से २१जी बस के शाम ६ बजे बाद के छूटने के समय लिखिए।','native_period','Normalize evening six to 18:00 and retain route/stop.',{'route_number':'21G','transport_mode':'bus','time':'18:00:00'})
add(i,'ताम्बरम स्टेशन से चेन्नई बीच की लोकल रेल के निर्धारित प्रस्थान बताओ।','native_schedule','Return published suburban departures for stated direction or a precise data limit.',{'transport_mode':'suburban_rail','timing_type':'departure'})
add(i,'एग्मोर मेट्रो की दोपहर २:३० के बाद वाली समय-सूची चाहिए।','native_clock','Normalize afternoon 2:30 to 14:30; no live arrival representation.',{'transport_mode':'metro','time':'14:30:00'})
add(i,'चेन्नई बीच से एमआरटीएस की समय-सारणी कहाँ तक उपलब्ध है? रवाना होने के समय बताइए।','schedule_request','Recognize published departure schedule request for MRTS.',{'transport_mode':'mrts','timing_type':'departure'})
add(i,'गिंडी से बस ५७० के रात ९ बजे के बाद के निर्धारित फेरे दिखाओ।','native_period','Preserve bus route and boarding location; normalize 21:00.',{'route_number':'570','transport_mode':'bus','time':'21:00:00'})
add(i,'गिंडी मेट्रो से ८ बजे के बाद कौन-कौन सी गाड़ियाँ छूटेंगी?','ambiguous_clock','Clarify morning versus evening; never silently choose one.',{'transport_mode':'metro','time':['08:00:00','20:00:00']},guard=True)
add(i,'सेंट्रल मेट्रो से कल की समय-सारणी बताओ।','ambiguous_day','Clarify whether कल means yesterday or tomorrow; never silently assign a date.',{'transport_mode':'metro'},guard=True)
add(i,'मेट्रो की समय-सारणी चाहिए, स्टेशन अभी नहीं लिखा है।','missing_station','Ask boarding stop or station; no invented timetable.',{'transport_mode':'metro'},guard=True)
add(i,'गिंडी मेट्रो से रात २५:६१ पर रवाना होने वाली ट्रेन बताओ।','invalid_clock','Reject or clarify impossible clock; do not normalize it into a valid time.',{'transport_mode':'metro'},guard=True)
add(i,'एग्मोर मेट्रो से सुबह ६ बजे से ८ बजे तक के प्रस्थान बताइए।','time_range','Preserve full range; explain unsupported time-range scope rather than answer after only one bound.',{'transport_mode':'metro'})
add(i,'गिंडी से रात १० बजे से पहले छूटने वाली मेट्रो की समय-सारणी चाहिए।','before_bound','Honor before-time request or state unsupported before-time scope; never silently invert into after-time.',{'transport_mode':'metro'})
i='mode_availability'
add(i,'सैदापेट से नंदनम तक सीधी मेट्रो सेवा है क्या?','direct_availability','Confirm only published mode-consistent directional connectivity; no full itinerary needed.',{'transport_mode':'metro'})
add(i,'ब्रॉडवे और अडयार के बीच बस चलती है या नहीं?','native_yes_no','Check static bus connectivity; absence of recorded connection is not proof of no service.',{'transport_mode':'bus'})
add(i,'ताम्बरम से चेन्नई बीच तक उपनगरीय रेल उपलब्ध है?','native_mode','Check suburban rail directional availability, without substituting metro.',{'transport_mode':'suburban_rail'})
add(i,'चेन्नई बीच से तिरुवान्मियूर जाने को एमआरटीएस सेवा मिलती है क्या?','mrts_availability','Check MRTS connection and disclose missing coverage if any.',{'transport_mode':'mrts'})
add(i,'कोयम्बेडु से वडपलनी मेट्रो की सुविधा मिल जाएगी?','colloquial_yes_no','Recognize service existence rather than journey route planning.',{'transport_mode':'metro'})
add(i,'गिंडी से हवाई अड्डे की सीधी बस है, इस बात की पुष्टि चाहिए।','assertion_confirmation','Check direct bus connectivity; do not treat user assertion as verified data.',{'transport_mode':'bus'})
add(i,'पेरम्बूर से सेंट्रल के बीच लोकल रेल नहीं चलती क्या?','negative_question','Answer availability on evidence; negative wording does not establish absence.',{'transport_mode':'suburban_rail'})
add(i,'अन्ना नगर से आलंदूर तक मेट्रो सेवा उपलब्ध है या बस ही लेनी होगी?','mode_contrast','Check requested metro availability without inventing alternate bus travel.',{'transport_mode':'metro'})
add(i,'सेंट्रल से हवाई अड्डे मेट्रो अभी रात ११ बजे चलती है क्या?','temporal_scope','Preserve requested time; static connectivity cannot certify operating availability at 23:00.',{'transport_mode':'metro','time':'23:00:00'})
add(i,'अडयार तक बस मिलती है क्या?','missing_origin','Ask starting place, preserving bus availability goal.',{'transport_mode':'bus'},guard=True)
add(i,'गिंडी से सीधी मेट्रो है क्या?','missing_destination','Ask destination; do not guess the desired connection.',{'transport_mode':'metro'},guard=True)
add(i,'गिंडी से नंदनम मेट्रो चलती है? रास्ते का विवरण नहीं चाहिए।','negated_route','Answer yes/no connectivity only; negated route detail is not a second goal.',{'transport_mode':'metro'})
i='fare_calculation'
add(i,'साधारण बस में चार स्टेज के सफर का किराया कितना होगा?','spelled_stage','Extract stage 4 and ordinary bus service, then use verified stage tariff.',{'transport_mode':'bus','stage_number':4,'service_type':'Ordinary Services'})
add(i,'एक्सप्रेस बस के ६ स्टेज का किराया बताइए।','devanagari_stage','Extract six stages and Express Services; no guessed amount.',{'transport_mode':'bus','stage_number':6,'service_type':'Express Services'})
add(i,'डीलक्स बस में आठ चरण चलने पर कितने रुपये लगते हैं?','spelled_stage_synonym','Recognize stage count eight and Deluxe service or clarify stage wording, never invent fare.',{'transport_mode':'bus','stage_number':8,'service_type':'Deluxe Services'})
add(i,'रात्रि सेवा की बस में पाँच स्टेज का भाड़ा जानना है।','native_service','Extract five stages and Night Services for tariff lookup.',{'transport_mode':'bus','stage_number':5,'service_type':'Night Services'})
add(i,'वातानुकूलित बस से १० स्टेज का सफर, टिकट के कितने पैसे बनेंगे?','native_service','Extract ten stages and Air Conditioned Services; return verified tariff or explicit source limit.',{'transport_mode':'bus','stage_number':10,'service_type':'Air Conditioned Services'})
add(i,'गिंडी मेट्रो से हवाई अड्डा मेट्रो तक एक यात्रा के टिकट की कीमत क्या है?','od_fare','Recognize metro origin-destination fare; use authoritative fare data only.',{'transport_mode':'metro'})
add(i,'एग्मोर मेट्रो से नंदनम मेट्रो का किराया बताओ, रास्ता मत समझाना।','negated_route','Fare only; negated route should not trigger multiple goals.',{'transport_mode':'metro'})
add(i,'साधारण एमटीसी बस में तीन स्टेज, किराया?','fragment','Recognize ordinary bus stage fare from a short fragment.',{'transport_mode':'bus','stage_number':3,'service_type':'Ordinary Services'})
add(i,'बस में ४ स्टेज जाने के पैसे कितने होंगे? सेवा का प्रकार नहीं मालूम।','missing_service_class','Ask bus service class rather than choosing Ordinary by default.',{'transport_mode':'bus','stage_number':4},guard=True)
add(i,'मेरा बस किराया निकाल दो, दूरी और स्टेज अभी नहीं बताए हैं।','missing_fare_basis','Ask stage number or journey endpoints; no fare guessed.',{'transport_mode':'bus'},guard=True)
add(i,'साधारण बस में ० स्टेज का किराया क्या है?','invalid_stage','Reject or clarify zero stage; never map invalid count to a valid tariff.',{'transport_mode':'bus','service_type':'Ordinary Services'},guard=True)
add(i,'साधारण बस के इकतीस स्टेज के किराए की रकम बताओ।','out_of_range_stage','Reject/clarify unsupported stage 31; do not drop count and provide another fare.',{'transport_mode':'bus','service_type':'Ordinary Services'},guard=True)
i='ticketing_and_passes'
add(i,'मेट्रो स्मार्ट कार्ड में कम से कम कितना रिचार्ज कराना पड़ता है?','card_policy','Recognize card policy and disclose absent authoritative ticket/pass rules; no invented minimum.')
add(i,'मेट्रो का क्यूआर टिकट खरीदने का नियम समझाइए।','qr_policy','Use ticketing family and state authoritative policy limitation.')
add(i,'एमटीसी का मासिक पास किन बसों में मान्य होता है?','pass_validity','Recognize monthly pass validity policy; do not guess coverage.')
add(i,'उपनगरीय रेल का सीजन पास लेने के लिए कौन से कागज चाहिए?','pass_documents','Recognize season-pass policy and disclose source limitation, not journey fare calculation.')
add(i,'एनसीएमसी कार्ड मेट्रो में चलाने के नियम क्या हैं?','native_card','Recognize NCMC policy; no unsupported validity assertion.')
add(i,'मेट्रो टोकन खो जाए तो बदलवाने का तरीका बताओ।','replacement_policy','Ticket/token policy; do not invent replacement rules.')
add(i,'पर्यटक पास एक ही दिन में कितनी यात्राओं के लिए चलता है?','tourist_policy','Recognize tourist pass usage policy; missing source must be explained.')
add(i,'बच्चों को मेट्रो टिकट में छूट किस उम्र तक मिलती है?','concession_policy','Recognize child ticket concession rule; do not guess age or concession percentage.')
add(i,'मेट्रो स्मार्ट कार्ड की बची रकम वापस मिलने का नियम क्या है?','refund_policy','Recognize card refund policy and give source limitation.')
add(i,'मेट्रो टिकट नकद लें या कार्ड से, कौन-कौन से भुगतान तरीके मान्य हैं?','payment_policy','Recognize accepted payment rules rather than exact fare.')
add(i,'बस का मासिक पास दूसरे व्यक्ति को देना मना है क्या?','negative_policy_question','Recognize transferability rules; do not assume allowed/disallowed without authoritative policy.')
add(i,'क्यूआर टिकट कब तक मान्य रहता है, कीमत नहीं पूछ रहा।','negated_fare','Handle ticket validity only; negated fare is not a separate goal.')
i='station_facilities'
add(i,'गिंडी मेट्रो स्टेशन पर बाइक खड़ी करने की पार्किंग मिलती है?','native_parking','Recognize parking facility goal; disclose unverified facility availability.')
add(i,'एग्मोर मेट्रो में पीने के पानी की जगह है क्या?','native_water','Correct facility family; do not claim unverified water availability.')
add(i,'कोयम्बेडु मेट्रो स्टेशन के अंदर शौचालय उपलब्ध हैं?','native_restroom','Recognize station restroom facility and explain source limitation.')
add(i,'वडपलनी मेट्रो पर यात्रियों के लिए बैठकर प्रतीक्षा करने का कमरा है?','waiting_room','Recognize waiting-room facility; no fabricated yes/no answer.')
add(i,'चेन्नई सेंट्रल मेट्रो में सामान रखने का क्लोक रूम मिलेगा?','cloakroom','Station amenity query remains facilities despite source limitation.')
add(i,'आलंदूर मेट्रो स्टेशन पर एटीएम लगा है क्या?','native_atm','Recognize ATM facility goal and disclose absent verification.')
add(i,'हवाई अड्डा मेट्रो स्टेशन में वाई-फाई मिलता है?','wifi','Recognize station Wi-Fi availability; avoid unsupported assurance.')
add(i,'नंदनम मेट्रो के पास कार पार्क करने की सुविधा पूछनी है।','car_parking','Correct facilities intent; unverified parking must not be presented as fact.')
add(i,'ताम्बरम रेलवे स्टेशन पर प्रतीक्षालय की सुविधा है या नहीं?','suburban_facility','Recognize physical station facility; disclose source coverage limit.')
add(i,'मेट्रो स्टेशन पर पानी और शौचालय की सुविधाएँ हैं क्या? स्टेशन नहीं बताया।','missing_station','Ask station or explain facility source limitation; never pick arbitrary station.',guard=True)
add(i,'गिंडी मेट्रो की पार्किंग पूछ रहा हूँ, व्हीलचेयर की जानकारी नहीं।','negated_accessibility','Handle parking only; negated accessibility phrase must not create another goal.')
add(i,'एग्मोर मेट्रो: बाथरूम है? जल्दी बता दीजिए।','colloquial_punctuation','Recognize ordinary restroom facility despite colloquial borrowing/punctuation; no invented fact.')
i='station_accessibility'
add(i,'गिंडी मेट्रो में व्हीलचेयर लेकर भीतर जाना संभव है?','wheelchair','Recognize wheelchair accessibility; report verified feature or precise absence of evidence.')
add(i,'एग्मोर मेट्रो स्टेशन में सीढ़ियाँ चढ़े बिना जाने के लिए लिफ्ट है क्या?','native_lift','Recognize lift accessibility, not generic facility; do not invent availability.',{'accessibility_feature':'lift','transport_mode':'metro'})
add(i,'कोयम्बेडु मेट्रो पर व्हीलचेयर के लिए ढलान वाला रैंप बना है?','native_ramp','Recognize ramp accessibility and use verified physical-station records.',{'accessibility_feature':'ramp','transport_mode':'metro'})
add(i,'वडपलनी मेट्रो में चलती सीढ़ी की सुविधा मिलती है?','native_escalator','Recognize escalator accessibility from native phrasing; no generic facility substitution.',{'accessibility_feature':'escalator','transport_mode':'metro'})
add(i,'आलंदूर मेट्रो पर दृष्टिबाधित यात्रियों के लिए स्पर्श पथ है?','native_tactile','Recognize tactile accessibility; report source record or limitation.',{'accessibility_feature':'tactile_paths','transport_mode':'metro'})
add(i,'हवाई अड्डा मेट्रो में दिव्यांगों के उपयोग वाला शौचालय है क्या?','accessible_toilet_contrast','Recognize accessible toilet rather than general restroom.',{'accessibility_feature':'accessible_toilet','transport_mode':'metro'})
add(i,'नंदनम मेट्रो पर बुज़ुर्गों के लिए सीढ़ी के बजाय लिफ्ट मिलेगी?','colloquial_access','Keep lift accessibility goal despite mention of stairs.',{'accessibility_feature':'lift','transport_mode':'metro'})
add(i,'सैदापेट मेट्रो में व्हीलचेयर से प्लेटफॉर्म तक पहुँचने की सुविधा की पुष्टि करो।','assertion_confirmation','Verify wheelchair accessibility; do not assume affirmative.')
add(i,'ताम्बरम रेल स्टेशन पर दिव्यांग रैंप उपलब्ध है?','suburban_scope','Recognize rail accessibility and honestly disclose missing verified record.',{'accessibility_feature':'ramp','transport_mode':'suburban_rail'})
add(i,'व्हीलचेयर के अनुकूल मेट्रो स्टेशन है क्या?','missing_station','Ask station; do not choose or imply every station is accessible.',{'accessibility_feature':'wheelchair','transport_mode':'metro'},guard=True)
add(i,'गिंडी मेट्रो पर लिफ्ट है? पार्किंग नहीं पूछी है।','negated_facility','Accessibility only; negated parking is not a second goal.',{'accessibility_feature':'lift','transport_mode':'metro'})
add(i,'सेंट्रल मेट्रो में बिना सीढ़ी चढ़े प्लेटफॉर्म पहुँचा जा सकता है?','implicit_accessibility','Recognize step-free access question; explain feature evidence limits without guessing.')
i='interchange_transfer'
add(i,'गिंडी पर मेट्रो से लोकल ट्रेन बदलने की जगह कहाँ है?','mode_pair','Recognize station transfer details; give only confirmed interchange evidence.')
add(i,'आलंदूर मेट्रो में नीली लाइन से हरी लाइन पर कैसे बदलूँ?','line_transfer','Interchange goal, not full endpoint journey; no unverified transfer directions.')
add(i,'चेन्नई सेंट्रल पर उपनगरीय रेल छोड़कर मेट्रो में जाने का जुड़ाव बताइए।','native_transfer','Recognize rail-to-metro transfer and state confirmed-interchange coverage limit.')
add(i,'कोयम्बेडु में बस अड्डे और मेट्रो स्टेशन के बीच बदलने का इंतजाम क्या है?','bus_metro','Recognize physical interchange details without inventing walkway/distance.')
add(i,'चेन्नई बीच पर लोकल रेल से एमआरटीएस में स्थानांतरण कहाँ होता है?','native_transfer','Keep inter-mode transfer goal and disclose source limit.')
add(i,'सेंट्रल मेट्रो में एक मेट्रो लाइन से दूसरी लाइन का इंटरचेंज समझाइए।','same_mode_lines','Recognize line interchange rather than mode availability or journey route.')
add(i,'ताम्बरम में ट्रेन से उतरकर बस पकड़ने वाला स्थानांतरण बिंदु है?','native_hub','Recognize transfer feasibility at named hub, not bus stop membership.')
add(i,'गिंडी स्टेशन पर बस से मेट्रो में बदलने की जानकारी चाहिए।','native_places','Recognize bus-to-metro interchange and verify before answering.')
add(i,'एग्मोर में रेल प्लेटफॉर्म से मेट्रो का जुड़ाव सीधा है क्या?','connection_yes_no','Confirm only verified physical transfer connection; no inferred direct link.')
add(i,'मेट्रो से बस में कहाँ बदलना होता है?','mode_pair_no_station','Recognize requested mode pair and ask location/scope or explain transfer source limit.',{'mode_from':'metro','mode_to':'bus'})
add(i,'यहाँ गाड़ी बदलने की सुविधा कहाँ है?','missing_location_modes','Ask station or both modes; do not guess referent.',guard=True)
add(i,'आलंदूर में लाइन बदलने का तरीका चाहिए, वहाँ की पार्किंग नहीं।','negated_facility','Answer interchange goal only; negated parking is not another question.')
i='nearest_transport'
add(i,'मरीना बीच के सबसे पास का बस स्टॉप कौन सा पड़ेगा?','native_landmark','Find nearest bus stop using source coordinates and label straight-line distance; do not claim walkable route.',{'transport_mode':'bus'})
add(i,'आईआईटी मद्रास से नज़दीकी मेट्रो स्टेशन बताइए।','native_landmark','Recognize nearest metro to IIT Madras; clarify unresolved landmark or use coordinate evidence.',{'transport_mode':'metro'})
add(i,'अन्ना नगर इलाके के पास सबसे निकट रेल स्टेशन कौन सा है?','native_locality','Use locality as spatial reference and requested rail mode; no invented precise proximity.',{'transport_mode':'suburban_rail'})
add(i,'अपोलो अस्पताल ग्रीम्स रोड के आसपास सबसे पास वाली बस पकड़ने की जगह बताओ।','landmark_colloquial','Recognize nearest bus stop to full hospital landmark; do not substitute journey planning.',{'transport_mode':'bus'})
add(i,'अडयार में निकटतम सार्वजनिक परिवहन स्टेशन ढूँढ़ दीजिए।','any_mode','Recognize locality-relative nearest transport; clarify unresolved locality or return verified coordinates.')
add(i,'चेपॉक स्टेडियम के नज़दीक कौन सा एमआरटीएस स्टेशन है?','native_landmark_mode','Preserve MRTS mode in nearest lookup.',{'transport_mode':'mrts'})
add(i,'फीनिक्स मार्केटसिटी के पास उतरने के लिए सबसे निकट बस स्टॉप क्या है?','landmark','Nearest bus stop goal; use recognized landmark coordinates or ask clarification.',{'transport_mode':'bus'})
add(i,'वेलाचेरी इलाके में सबसे पास का मेट्रो ठहराव बताओ।','locality_mode','Nearest metro relative to Velachery locality; no assumption that a local metro station exists.',{'transport_mode':'metro'})
add(i,'मरीना बीच से सबसे नज़दीकी उपनगरीय रेल स्टेशन कितना दूर है?','nearest_distance','Return nearest coordinate distance with straight-line qualification, no fabricated walking distance.',{'transport_mode':'suburban_rail'})
add(i,'पास का बस स्टॉप बता दो, जगह अभी नहीं लिखी है।','missing_reference','Ask nearby landmark or locality; do not assume user GPS location.',{'transport_mode':'bus'},guard=True)
add(i,'मरीना बीच का सबसे पास मेट्रो स्टेशन चाहिए; वहाँ पहुँचने का रास्ता नहीं पूछ रहा।','negated_route','Nearest only; negated route request must not create multiple goals.',{'transport_mode':'metro'})
add(i,'गिंडी इलाके के आसपास निकटतम स्टेशन, कृपया... मेट्रो वाला।','punctuation_colloquial','Use Guindy locality for nearest metro request despite punctuation.',{'transport_mode':'metro'})
i='realtime_status_query'
add(i,'२१जी बस इस वक्त कहाँ पहुँची है, उसकी जीपीएस स्थिति दिखाओ।','live_gps','Recognize realtime goal and explicitly refuse absent live feed; no guessed vehicle position.')
add(i,'गिंडी मेट्रो अभी कितनी देरी से चल रही है?','live_delay','Realtime delay family; explain missing external source without claiming on-time status.')
add(i,'सेंट्रल मेट्रो में अभी यात्रियों की भीड़ कितनी है?','live_crowd','Recognize current crowd density and refuse unavailable live information.')
add(i,'ताम्बरम से चेन्नई बीच वाली लोकल ट्रेन इस समय कहाँ रुकी है?','live_location','Recognize realtime vehicle position rather than published schedule.')
add(i,'हवाई अड्डा मेट्रो की सेवा अभी बंद पड़ी है या सामान्य चल रही है?','live_disruption','Recognize current disruption/running status; static connectivity is insufficient.')
add(i,'बस ५७० का अभी अगला आगमन कितने मिनट में होगा, लाइव बताइए।','live_eta','Refuse unavailable live ETA without presenting scheduled time as actual arrival.')
add(i,'नीली लाइन पर अभी कोई दुर्घटना से रुकावट है क्या?','live_incident','Recognize live incident status, disclose lack of live operator feed.')
add(i,'वडपलनी मेट्रो की लिफ्ट आज अभी काम कर रही है?','live_accessibility','Live equipment operation is realtime, not static lift availability; no operational assurance.')
add(i,'मेट्रो की इस समय की असली देरी चाहिए, समय-सारणी वाली नहीं।','negated_schedule','Realtime only; negated timetable is not a second goal.')
add(i,'चेन्नई बीच से एमआरटीएस ट्रेन अभी निकल चुकी है या नहीं?','live_departure','Recognize actual present departure state and refuse unsupported live status.')
add(i,'२७डी बस में अभी सीट खाली मिलेगी? बस की मौजूदा भीड़ पूछ रहा हूँ।','live_capacity','Recognize vehicle realtime capacity/crowding and no guessed seats.')
add(i,'आलंदूर में अभी मेट्रो प्लेटफॉर्म बंद है क्या, तुरंत की स्थिति बताओ।','live_platform','Realtime disruption question; disclose external-source need, not facilities fact.')
i='out_of_scope'
add(i,'चेन्नई में कल बारिश होगी क्या, मौसम बताइए।','weather','Reject weather as outside Chennai public-transport assistant scope.')
add(i,'हवाई अड्डे के लिए मेरे नाम से टैक्सी बुक कर दो।','cab_transaction','Reject ride-hailing booking; do not claim booking performed.')
add(i,'मुझे एग्मोर के पास अच्छा होटल आरक्षित करके दे दो।','hotel_transaction','Reject hotel booking, with no fabricated reservation.')
add(i,'चेन्नई से दिल्ली की उड़ान का टिकट खरीदो।','flight_transaction','Reject flight purchase and intercity flight scope.')
add(i,'बैंगलुरु जाने वाली लंबी दूरी की ट्रेन में सीट आरक्षित करो।','intercity_transaction','Reject intercity reservation request; no booking performed.')
add(i,'मेरे लिए सेंट्रल मेट्रो के दो टिकट अभी खरीदकर भुगतान कर दो।','transit_purchase','Transactional ticket purchase is outside supported informational ticketing; do not claim payment.')
add(i,'घर का बिजली बिल कितना बाकी है, जाँच दो।','unrelated_account','Reject unrelated utility-account request.')
add(i,'चेन्नई की सबसे स्वादिष्ट बिरयानी कहाँ मिलेगी?','food','Reject restaurant/food recommendation as outside transit scope.')
add(i,'मेरी मोबाइल लोकेशन से पता करो मैं अभी कहाँ हूँ।','device_location','Do not imply GPS/device access; reject outside scope.')
add(i,'मेट्रो विषय छोड़ो, मुझे गणित का सवाल हल करके दो: सात गुणा आठ कितना?','explicit_scope_shift','Reject unrelated arithmetic despite transport keyword; no transit intent selected.')
add(i,'मेरे स्मार्ट कार्ड से बैंक खाते में पैसे भेज दो।','money_transaction','Reject financial transaction rather than give unsupported card transfer policy.')
add(i,'नमस्ते! आज का राशिफल सुनाओ।','smalltalk_plus_oos','Reject horoscope request politely; no transport facts invented.')
# Additional contrasts and ambiguity guards, bringing the independently authored set to 200.
add(None,'गिंडी मेट्रो से हवाई अड्डे का किराया बताइए और पहली ट्रेन का समय भी बताइए।','multiple_goals','Ask which fare or first-service question to answer first; no arbitrary single operation.',guard=True)
add(None,'ब्रॉडवे से २१जी बस के सभी स्टॉप बताओ और अभी बस कहाँ है यह भी बताओ।','multiple_goals','Clarify separate stop sequence and live location goals; do not answer only one silently.',guard=True)
add(None,'आलंदूर मेट्रो में लिफ्ट है क्या, और पार्किंग की सुविधा भी बताओ।','multiple_goals','Clarify separate accessibility and facility goals; do not collapse the two.',guard=True)
add(None,'मरीना बीच के पास का बस स्टॉप बताइए और सेंट्रल से वहाँ पहुँचने का रास्ता बताइए।','multiple_goals','Clarify nearest-stop and journey-planning goals rather than choose one arbitrarily.',guard=True)
add(None,'गिंडी मेट्रो की सुविधा?','intent_ambiguity','Ask whether user means service, station amenities, accessibility, or another specific goal.',guard=True)
add(None,'ताम्बरम, ट्रेन, कल — बस इतनी ही जानकारी है।','incomplete_ambiguous','Ask actual transport goal and day; do not fabricate a route, timetable, fare, or date.',guard=True)
add('fare_calculation','साधारण बस में किराया दस स्टेज का चाहिए, चार स्टेज का नहीं।','negated_stage','Extract only positive ten stages; negated four is not another fare scope.',{'transport_mode':'bus','stage_number':10,'service_type':'Ordinary Services'})
add('scheduled_departure','गिंडी मेट्रो की समय-सारणी रात ११:७५ के बाद बताइए।','invalid_minute','Reject or clarify impossible minute 75; do not silently convert to another clock.',{'transport_mode':'metro'},guard=True)
assert len(cases)==200
assert len({c['query'] for c in cases})==200
assert all(c['query'].encode('utf-8').decode('utf-8')==c['query'] for c in cases)
assert all('\ufffd' not in c['query'] for c in cases)
(BASE/'cases.json').write_text(json.dumps(cases,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Authored',len(cases),'Hindi cases before inference.')
