"""Serialize manual judgments after reading all 200 baseline replies; no API calls."""
import json
from pathlib import Path
from collections import Counter, defaultdict
P=Path(__file__).resolve().parent
base=json.loads((P/'baseline.json').read_text())
cases=json.loads((P/'cases.json').read_text())
assert [c['id'] for c in base]==[c['id'] for c in cases]
CATS={'G':'goal_correct','S':'safe_limitation','L':'legitimate_clarification','R':'recognition_failure','U':'unsafe_or_wrong_answer','N':'needs_review'}
M={}
def row(n,cat,issue,notes):
    assert n not in M
    M[n]={'id':f'HG200_{n:03}','category':CATS[cat],'notes':notes,'issue_type':issue}
def same(ns,cat,issue,notes):
    for n in ns: row(n,cat,issue,notes)

# 001-024: Manually reviewed query, slots, status and source message for every ID.
row(1,'S','source_limit; secondary_origin_not_retained','Correct journey family and metro topology refusal. Returned slots retain Teynampet destination but omit supplied Vadapalani origin; no itinerary claimed, so source limitation remains primary.')
row(2,'S','source_limit','Correct metro journey family, both endpoints retained; no mode-consistent published metro topology.')
row(3,'R','negation_wrong_family','Route request explicitly excludes ticket rate; fare_calculation/entity clarification answers the wrong family.')
row(4,'R','wrong_family_missing_origin','Missing-origin route request becomes route_stop_sequence; source refusal does not request absent origin.')
row(5,'R','wrong_family_missing_destination','Missing-destination journey request becomes interchange_transfer and a transfer-source refusal.')
row(6,'R','wrong_family_preference','Metro journey with least-changes preference becomes interchange_transfer.')
row(7,'L','canonical_entity_ambiguity','Correct journey family and bus origin preserved; CMBT has multiple bus physical-stop candidates. Clarification avoids guessing destination.')
row(8,'S','source_limit; secondary_roles_and_preference_not_retained','Correct metro journey source refusal, but returned destination is Ashok Nagar (the origin); Saidapet and quickest preference are absent. No narrower route was asserted.')
row(9,'S','source_limit; secondary_endpoints_not_retained','Correct metro journey source refusal and Alandur via retained. Anna Nagar Tower and Airport endpoints are absent from returned slots; waypoint itinerary is not fulfilled.')
row(10,'R','wrong_family_constraint','Direct-only journey request becomes mode_availability; also LIC is retained without Nandanam origin or direct preference.')
row(11,'S','source_limit','Correct suburban journey family, Tambaram-to-Chennai Beach direction and mode retained; matching topology is unavailable.')
row(12,'R','negation_mode_conflict','Explicit metro request excluding bus becomes mode_availability and asks to choose metro or bus; negated mode is treated as requested.')
row(13,'S','source_limit; extraction_unverified','Explicit local/metro combined journey is recognized as multimodal; blanket missing confirmed transfer-graph refusal precedes endpoint extraction, so no itinerary goal is fulfilled.')
row(14,'R','wrong_family_mode_chain','Combined bus/metro itinerary becomes point_to_point_route and a request to select one mode.')
row(15,'S','source_limit; extraction_unverified','Local-train/metro combined journey family correctly selected; absent confirmed multimodal graph prevents itinerary, with no extracted scope exposed.')
row(16,'S','source_limit; extraction_unverified','Bus-to-metro journey family correctly selected; blanket confirmed-graph limitation, no travel steps asserted.')
row(17,'R','wrong_family_missing_origin','Multimodal journey with absent start becomes first_and_last_service and a one-mode prompt.')
row(18,'S','source_limit_before_missing_scope','Multimodal family correct but source refusal precedes clarification of explicitly absent destination. Safe graph limitation is primary; missing destination is still unresolved.')
row(19,'R','wrong_family_mode_chain_preference','Explicit cheapest metro/bus combination becomes single-mode route and asks user to choose one mode.')
row(20,'R','wrong_family_waypoint','Local/metro itinerary via Central becomes point_to_point_route, with only metro mode retained; broad refusal does not rescue wrong family.')
row(21,'S','source_limit; extraction_unverified','Explicit MRTS/bus travel chain recognized as multimodal; graph absent and no itinerary asserted.')
row(22,'S','source_limit; optimization_unverified','Bus/metro journey recognized as multimodal; graph refusal is safe, but shortest preference/endpoints are not exposed or fulfilled.')
row(23,'S','source_limit; extraction_unverified','Combined journey family retained despite negated metro-only wording; confirmed multimodal graph absent.')
row(24,'S','source_limit; extraction_unverified','Indirect combined local/bus itinerary request recognized as multimodal; source refusal does not claim an itinerary.')

# 025-048: Stop topology/membership and absent-route inputs.
row(25,'S','source_limit','Exact 570S suffix and bus mode retained; no published sequence available for the requested route.')
row(26,'S','partial_topology','21 G correctly normalized to 21G and sourced sequences returned, but full requested list is only partial. Response discloses four unusable links and uncovered variants; not full goal fulfillment.')
row(27,'G','answered_published_scope','102-A correctly normalized to 102A; two complete sourced directional sequences returned with provisional operation caveat.')
same([28,29],'S','source_limit','Correct sequence family, explicit metro mode and named line retained; matching metro topology source unavailable.')
row(30,'S','partial_topology','29C stop list recognized despite negated fare. Returned sourced variants disclose partial coverage and uncovered route IDs; requested complete list is not fully fulfilled.')
row(31,'S','source_limit','M1 route prefix and bus mode preserved; no mode-consistent sequence for exact route.')
row(32,'G','answered_native_digit_scope','Native १०२A correctly normalized to 102A; two complete sourced directional sequences returned with provisional caveat.')
row(33,'R','supplied_route_missed','२५R is clearly supplied but route slot absent and prompt asks for route; numeral/route-cue recognition failed.')
row(34,'L','genuinely_missing_route','Correct sequence family asks for the route/line that the query explicitly says is absent.')
row(35,'R','supplied_suffix_route_missed','Explicit 102K# variant is not extracted; route clarification asks for an already supplied identifier.')
row(36,'G','answered_directional_sequences','Exact 27D retained and five sourced sequences include both directions; full payload is qualified as published topology, not running service.')
row(37,'R','supplied_stop_missed','T Nagar stop is supplied but prompt asks for stop; absence of canonical alias is not genuinely missing user input.')
row(38,'L','canonical_entity_ambiguity','Correct membership family, 21G and bus retained; ten distinct Guindy bus physical-stop candidates justify a stop choice.')
row(39,'R','wrong_family_supplied_route_missed','Adyar membership on 102A becomes route_stop_sequence, with 102A omitted and requested again.')
row(40,'S','source_limit','570 S normalized to 570S, Sholinganallur and membership goal retained; source says exact route or stop absent.')
row(41,'R','wrong_family_line_membership','Green Line membership of Guindy becomes interchange_transfer refusal.')
row(42,'R','wrong_family_line_membership','Egmore membership on Blue Line becomes sequence listing refusal; no membership operation selected.')
row(43,'R','wrong_family_answered_sequence','२१G normalized successfully but specific Saidapet membership is answered with an entire route sequence. Sourced list is not the requested yes/no membership result.')
row(44,'R','supplied_native_suffix_route_missed','१०२-C supplied explicitly, but only Thiruvanmiyur stop retained; route identifier requested again.')
row(45,'L','canonical_ambiguity_and_missing_route','Guindy bus physical stop is genuinely ambiguous and route is explicitly absent. Asking for a stop choice is legitimate, though route remains unresolved.')
row(46,'R','wrong_family_missing_stop','Query explicitly says membership stop is absent; response lists 25R route stops rather than asking which stop.')
row(47,'R','supplied_route_missed_with_ambiguity','Ashok Pillar bus candidates are genuinely multiple, but explicit 27D is absent from slots. Genuine entity ambiguity does not excuse losing the supplied route scope.')
row(48,'R','wrong_family_supplied_suffix_route_missed','102K# membership becomes sequence family and prompt requests already supplied route variant.')

# 049-072: Service bounds and frequency.
row(49,'S','source_limit','Correct first-service goal with Guindy metro station and first timing retained; metro schedule source absent.')
row(50,'U','wrong_family_unsafe_partial_answer','Last 25R bus from Poonamallee becomes general scheduled_departure. Route 25R and last bound are dropped; OK answer lists unrelated 597A/66P departures around midnight, falsely fulfilling a different scope.')
row(51,'R','explicit_local_mode_not_used','Last-service family is correct, but explicit local train is not retained as suburban mode. Tambaram candidates include bus/hub/rail and ask avoidable cross-mode ambiguity.')
row(52,'R','supplied_route_missed_with_ambiguity','First-service family and CMBT ambiguity are recognized, but explicit 27D route is absent; generic clarification loses route constraint.')
row(53,'R','false_multiple_goals','First and last bounds are one GET_FIRST_LAST_SERVICE goal on 102 from Broadway. Generic multiple-scope clarification incorrectly treats this as competing goals.')
row(54,'R','wrong_family_missing_station','First metro with explicit absent station becomes interchange_transfer source refusal, rather than first-service scope.')
row(55,'R','supplied_route_missed','Absent boarding stop legitimately needs input, but supplied 21G was dropped from first/last slots; not a fully legitimate clarification.')
row(56,'R','false_multiple_goals_temporal','Ambiguous kal for one last train becomes multiple_goals rather than temporal clarification; actual question has one temporal ambiguity.')
row(57,'R','false_multiple_goals_clock_bound','One last-bus query with explicit night clock and route 102 gets competing-scope clarification instead of retaining/limiting the unsupported clock bound.')
row(58,'R','supplied_native_route_and_origin_missed','५७०S and Kelambakkam were supplied, but neither route nor origin retained; asks again for boarding stop.')
row(59,'R','negated_live_wrong_family','Published first metro explicitly excludes live; response selects realtime_status_query and live refusal.')
row(60,'R','wrong_family_waypoint','Pehli bus explicitly asks first service, but selected family is scheduled_departure. Safe waypoint limitation does not rescue wrong family.')
row(61,'R','supplied_route_missed','25R supplied before stop name is not extracted; correct headway family asks for a route already provided.')
row(62,'L','canonical_entity_ambiguity','Correct frequency family and bus 102 preserved; three Broadway bus physical-stop candidates justify choosing stop.')
row(63,'R','wrong_family_headway','Explicit scheduled frequency on Green Line becomes scheduled_departure; matching source refusal still wrong family.')
row(64,'R','line_mode_context_not_used','Blue Line headway goal selected but line context does not qualify Guindy as metro; bus/metro/rail ambiguity prompt is avoidable with unambiguous line context.')
row(65,'R','supplied_route_and_plural_mode_missed','21 G and buses explicitly supplied, but slots empty and rail/bus Saidapet candidates mixed. Supplied route/mode not retained.')
row(66,'R','supplied_native_route_missed','Correct frequency family and Broadway bus ambiguity, but supplied १०२A route is absent.')
row(67,'R','wrong_family_missing_route','Frequency with explicitly unknown route becomes sequence-listing clarification.')
row(68,'R','wrong_family_supplied_route_missed','Headway with missing stop becomes sequence family, which also asks for already supplied 27D route.')
row(69,'R','wrong_family_negated_live_false_multigoal','Scheduled gap explicitly excludes live wait; selected scheduled_departure and false multiple-scope clarification instead of headway.')
row(70,'R','wrong_family_supplied_route_missed','M1 evening headway becomes first_and_last_service; M1/period scope omitted from source refusal.')
row(71,'R','wrong_family_waypoint','Frequency via Guindy becomes scheduled_departure; waypoint refusal safe but family wrong.')
row(72,'R','wrong_family_supplied_route_missed','kal correctly triggers temporal clarification, but frequency becomes scheduled_departure and explicit 25R is dropped.')

# 073-096: Departures, clock/day behavior and existence.
row(73,'G','answered_scheduled_scope','07:15 explicit morning clock and Poonamallee stop retained; five published departures at/after 07:15 have schedule/source/provisional caveat.')
row(74,'S','source_limit','25R, 18:40, bus mode and Poonamallee stop retained; no matching published departures found, no live/negative availability claim.')
row(75,'R','supplied_route_missed_with_ambiguity','Correct departure family, AM clock and genuine Broadway bus ambiguity, but supplied 102 before ke not extracted.')
row(76,'S','source_limit; secondary_daypart_time_wrong','Correct departure family and metro source refusal. Returned 06:20 contradicts explicit shaam 6:20 (18:20); blanket refusal prevents factual timetable misanswer but exposes time-normalization defect.')
row(77,'L','canonical_entity_ambiguity','Native २१G route and night ९:१० clock normalize correctly; Saidapet bus physical candidates genuinely ambiguous.')
row(78,'R','wrong_family_missing_station','Explicit departures at 6 PM with station absent becomes route_stop_sequence and asks for route/line instead.')
row(79,'L','genuine_bare_clock_ambiguity','Bare 9 baje preserved as 09:00/21:00 candidates and requests time/day clarification; no AM default.')
row(80,'L','canonical_ambiguity; invalid_clock_unverified','CMBT genuinely has bus/metro candidates, so asking which physical stop is legitimate and no invalid-clock answer executes. 26:75 is not retained or explicitly acknowledged; invalid-clock handling remains unverified behind this ambiguity.')
row(81,'R','supplied_route_missed_with_temporal_ambiguity','Ambiguous kal appropriately clarified but explicit 25R omitted; partial recognition is not a fully legitimate clarification.')
row(82,'S','unsupported_waypoint_scope; secondary_route_unretained','Correct departure goal, AM clock retained and explicit waypoint-filter limitation. Returned slots omit supplied 102 and endpoints; no partial timetable claimed.')
row(83,'R','false_multiple_goals_before_clock','One departure scope with before 5 PM is incorrectly treated as multiple goals; route/clock discarded instead of explicit unsupported-before limitation.')
row(84,'R','false_multiple_goals_negated_live','One 27D departure clock with negated current arrival becomes multiple_goals, dropping route/time scope.')
row(85,'L','canonical_entity_ambiguity','Correct bus-connectivity family; supplied Saidapet and Guindy have multiple physical bus candidates, so stop choice is legitimate.')
row(86,'S','source_limit; secondary_endpoint_roles_not_retained','Correct metro availability refusal; Alandur retained as destination and Airport absent, although query states a between-pair. No connection asserted; endpoint representation remains defective.')
row(87,'S','source_limit','Correct suburban connectivity family and both endpoints/mode retained; matching published topology unavailable.')
row(88,'S','source_limit; secondary_destination_not_retained','Correct MRTS connectivity refusal and Velachery origin; Thirumayilai destination absent from returned slots. No route/connection assertion made.')
row(89,'R','wrong_family_connectivity','Porur-to-CMBT bus existence becomes interchange_transfer source refusal.')
row(90,'S','source_limit; secondary_destination_not_retained','Correct metro connectivity refusal and Nehru Park origin; Anna Nagar Tower destination absent. Blanket source gate prevents a connection assertion.')
row(91,'R','supplied_destination_missed','Origin genuinely absent, but Airport destination supplied and also requested again. Missing canonical recognition cannot be counted as truly absent input.')
row(92,'R','explicit_local_mode_not_used','Pallavaram origin with local mode and absent destination becomes cross-mode entity ambiguity including bus and rail, with local mode unretained.')
row(93,'R','negated_route_wrong_family','Connectivity explicitly excludes directions; response selects sequence family and metro topology refusal.')
row(94,'R','wrong_family_dated_availability','Future bus availability becomes first_and_last_service with false multiple-goal clarification; dated connectivity scope not recognized.')
row(95,'S','source_limit; secondary_destination_not_retained','Correct availability source refusal and 23:00/aaj/metro retained; Airport destination omitted. No claim of operation today made.')
row(96,'R','negated_mode_conflict','Local train explicitly requested and bus excluded, but prompt asks to choose suburban or bus, counting negated bus as requested mode.')

# 097-120: Fares and policy.
row(97,'G','answered_dated_stage_tariff','Ordinary stage 6 preserved; INR 10 includes source, government order and 2018 effective date with current-fare caveat. No claimed current price guarantee.')
row(98,'R','supplied_reversed_plural_stage_missed','11 stages explicitly supplied before the plural stage noun; missing-stage prompt fails to retain stage count while Express class is retained.')
row(99,'R','supplied_reversed_stage_missed','8 stage explicitly supplied before stage; missing-stage prompt fails to retain stage count while Deluxe class is retained.')
row(100,'G','answered_dated_stage_tariff','Night stage 3 retained; INR 15 returned with official source, government order, effective date and current-fare caveat.')
row(101,'S','requested_class_source_absent','AC stage 7 and bus mode retained; absent verified AC tariff is reported, with no class substitution.')
row(102,'R','supplied_native_stage_missed','Ordinary ६ stage clearly supplied but stage slot missing; prompt requests already supplied stage.')
row(103,'S','source_limit','Correct token fare family, Guindy-to-High Court metro endpoints and token retained; no verified fare record returned.')
row(104,'R','wrong_family_amount_vs_policy','Smart-card journey amount explicitly requested, but selected ticket/pass policy refusal instead of fare-calculation goal.')
row(105,'R','wrong_family_bus_od_fare','Bus OD fare with no known stage becomes interchange_transfer source refusal.')
row(106,'L','genuinely_missing_fare_scope','Fare family and bus retained; query explicitly lacks OD pair and stage, so requesting them is legitimate.')
row(107,'G','answered_dated_disclosed_default','Explicit stage 12 retained; Ordinary default disclosed in response and data along with official source/effective date and current-price caveat.')
row(108,'L','canonical_entity_ambiguity','Correct metro fare family despite negated route directions; two Egmore metro physical IDs justify origin choice and Central destination retained.')
same(list(range(109,121)),'S','ticket_policy_source_absent; extraction_unverified','Correct ticketing_and_passes family; blanket refusal states authoritative ticket/pass policy table absent. No invented policy or transaction flow; ticket/mode extraction is bypassed/unverified and policy goal remains unfulfilled.')

# 121-156: Source refusals are safe but not fulfillment; wrong family remains failure.
for n in [121,123,125,126,127,130,131,132]:
 row(n,'S','facility_source_unverified; extraction_unverified','Correct station_facilities family with explicit unverified-facility limitation. No amenity availability invented; station/facility extraction bypassed/unverified and user goal not answered.')
row(122,'R','wrong_family_hindi_facility','Drinking-water amenity expressed as paani peene becomes interchange_transfer source refusal.')
row(124,'R','wrong_family_transit_amenity_oos','ATM inside High Court metro is an in-domain station facility/source-limited goal, but classified out_of_scope.')
row(128,'R','wrong_family_missing_facility_station','Parking query with station absent becomes interchange_transfer rather than facilities scope or station clarification.')
row(129,'R','wrong_family_missing_facility_station','Drinking-water station query with absent station becomes interchange_transfer.')
for n in [133,134,135,137,138,139,140,144]:
 row(n,'S','accessibility_source_absent; extraction_unverified','Correct station_accessibility family; no verified accessibility values explicitly disclosed. No availability flag invented; feature/station extraction bypassed/unverified and goal remains unfulfilled.')
row(136,'R','wrong_family_accessibility','Escalator verified-info request becomes ticketing_and_passes source refusal.')
row(141,'R','wrong_family_missing_accessibility_station','General lift status with absent station is not explicitly live vehicle status, but becomes realtime_status_query.')
row(142,'R','wrong_family_missing_accessibility_station','Accessible-toilet query with absent station becomes interchange_transfer.')
row(143,'R','negated_facility_wrong_family','Lift info explicitly excludes parking; station_facilities refusal selects the negated goal family.')
row(145,'R','wrong_family_transfer','Central metro-to-local transfer becomes ticketing_and_passes refusal.')
for n in [146,147,150,153,154,156]:
 row(n,'S','confirmed_transfer_source_absent; extraction_unverified','Correct interchange_transfer family; snapshot has no confirmed interchange records, so no verified switch/walk instructions are claimed. Transfer modes/location extraction bypassed/unverified.')
row(148,'R','wrong_family_transfer_mode_conflict','Bus-to-metro transfer at CMBT becomes mode_availability and asks to choose one mode instead of preserving mode pair.')
row(149,'R','wrong_family_transfer_mode_conflict','Metro-to-suburban transfer at St Thomas Mount becomes point_to_point_route and a single-mode prompt.')
row(151,'S','source_limit_before_missing_scope','Correct interchange family; blanket no-confirmed-records refusal precedes missing station/mode-pair clarification. No transfer asserted, absent scope remains unresolved.')
row(152,'R','wrong_family_walking_transfer','Metro-to-bus walking transfer from High Court becomes ticketing_and_passes source refusal.')
row(155,'R','negated_fare_wrong_family','Line interchange explicitly excludes fare; selected fare_calculation and asks for starting stop.')

# 157-180: Geometric nearest and live refusal boundaries.
row(157,'G','answered_geometric_published_scope','Marina Beach anchor and requested metro mode retained. Sourced metro candidates and distance returned with straight-line/provisional and unverified walking caveats; this proves geometric nearest only, not current operation.')
row(158,'R','false_multiple_goals_nearest','One IIT Madras reference and one bus target mode get false competing-scope clarification; landmark/target relation not retained.')
row(159,'L','canonical_entity_ambiguity','Four Apollo Hospital POI candidates genuinely ambiguous; correct nearest family and metro target retained.')
row(160,'R','supplied_locality_missed','T Nagar reference supplied but landmark/locality slot absent; prompt requests already supplied place.')
row(161,'R','false_multiple_goals_nearest','One Besant Nagar reference with bus target is treated as multiple goals instead of a proximity lookup.')
row(162,'L','canonical_entity_ambiguity','Mylapore has two canonical reference candidates; nearest family and MRTS requested mode retained. Candidate choice avoids guessing reference coordinates.')
row(163,'L','genuinely_missing_location','Correct nearest family and metro mode; user explicitly says location absent, so landmark/locality prompt is appropriate.')
row(164,'R','false_entity_from_missing_location_prose','Reference location explicitly absent but six spurious bus entity candidates are offered, mode omitted; clarification invents an entity ambiguity from explanatory prose.')
row(165,'R','false_multiple_goals_anchor_target_modes','Single Anna Nagar Tower metro reference plus bus target is incorrectly multiple scopes; cannot distinguish anchor mode from desired nearest mode.')
row(166,'R','negation_false_multiple_goals_nearest','One Marina Beach reference and metro target explicitly excluding bus becomes multiple scopes; negation not honored.')
row(167,'R','wrong_family_walking_metric','Nearest metro by walking distance becomes point_to_point_route source refusal; unsupported walking metric should remain nearest family.')
row(168,'N','locality_to_stop_anchor_needs_review','Correct nearest family but geographic Thiruvanmiyur is silently anchored to exact BUS_3247299914, returning itself at 0 m. No independent canonical locality coordinates were supplied; whether this fulfills intended locality scope needs review. Not counted as goal_correct.')
for n in [169,173,177,179]:
 row(n,'S','external_live_source_required; extraction_unverified','Correct realtime_status_query family with explicit live-source refusal. No current location/ETA/crowd invented; route/location extraction bypassed/unverified and live goal remains unfulfilled.')
row(170,'R','wrong_family_live_delay','Current metro lateness becomes first_and_last_service and a static schedule source refusal.')
row(171,'R','wrong_family_live_crowd_false_multigoal','Current crowd goal becomes service_frequency with false multiple-scope clarification.')
row(172,'R','wrong_family_live_eta','Real time arrival countdown becomes scheduled frequency, returning insufficient static departures rather than live-source limitation.')
row(174,'R','wrong_family_live_disruption','Current MRTS disruption becomes service_frequency and static timetable refusal.')
row(175,'R','wrong_family_native_route_live','Native २१G normalizes but right-now vehicle location becomes route_stop_membership and asks for stop.')
row(176,'R','wrong_family_live_delay_negation','Current local delay explicitly excludes timetable, but first_and_last_service/false competing scope selected.')
row(178,'R','negated_sequence_wrong_family','Current 27D location explicitly excludes route stops; sequence family selected and route also missed.')
row(180,'R','wrong_family_live_disruption','Current Blue Line suspension/latest status becomes ticketing_and_passes source refusal.')

# 181-200: Rejection scope and multiple-goal/competing-scope guards.
row(181,'R','wrong_family_food_order','Food delivery near transit entity becomes ticket policy refusal rather than domain rejection.')
row(182,'G','correct_domain_rejection','Explicit Ola cab booking correctly rejected as out_of_scope; no public-transit answer pretends to book cab.')
row(183,'G','correct_domain_rejection','Hotel booking near Chennai Central correctly rejected as out_of_scope.')
row(184,'R','wrong_family_weather','Weather/rain question becomes service_frequency and asks for station/route.')
row(185,'R','wrong_family_flight_fare','Intercity flight ticket cost becomes transit fare_calculation and asks for local fare stage/OD inputs.')
row(186,'R','wrong_family_intercity_booking','Bangalore private sleeper reservation becomes local bus availability and asks for local endpoints.')
row(187,'R','wrong_family_restaurant_booking','Restaurant table reservation near Central becomes station_facilities refusal.')
row(188,'R','wrong_family_housing_rent','Flat rent/broker request becomes transit fare entity clarification.')
row(189,'R','wrong_family_cinema_schedule','Cinema showtime becomes transport frequency and missing stop/route prompt.')
row(190,'R','negated_transit_wrong_family_cricket','Cricket-score request explicitly excludes bus route, but ticket/pass policy refusal selected.')
row(191,'R','negated_transit_wrong_family_repair','Laptop repair explicitly excludes metro; ticket/pass policy refusal selected.')
row(192,'R','wrong_geography_policy','Mumbai local pass policy explicitly excludes Chennai; Chennai ticket-policy family chosen rather than geography rejection.')
row(193,'R','competing_routes_not_recognized','Two explicit routes 25R and 102 should clarify one scope, but response says route missing instead of acknowledging competing supplied routes.')
row(194,'L','genuine_competing_stages','Two explicit Ordinary stage values correctly trigger one-scope clarification; neither silently executed.')
row(195,'L','genuine_competing_clocks','Two explicit AM/PM clocks correctly trigger one-scope clarification; no clock silently selected.')
row(196,'L','genuine_competing_reference_locations','Two nearest anchors correctly trigger competing-scope clarification; neither silently selected.')
row(197,'R','multiple_goals_one_goal_dropped','Explicit route plus fare receives only fare source refusal; route goal/candidate is lost.')
row(198,'L','genuine_multiple_families','Parking plus lift correctly clarifies multiple goals and exposes both station_facilities and station_accessibility candidate families.')
row(199,'R','multiple_goals_live_goal_dropped','Membership plus GPS location receives membership-only entity clarification; live goal/candidate absent and supplied 102A route omitted.')
row(200,'L','genuine_competing_destinations','Two destinations in one bus journey correctly trigger scope clarification instead of silently dropping an endpoint.')

assert set(M)==set(range(1,201)), sorted(set(range(1,201))-set(M))
A=[M[n] for n in range(1,201)]
(P/'assessment.json').write_text(json.dumps(A,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
counts=Counter(a['category'] for a in A)
per=defaultdict(Counter)
for c,a in zip(cases,A):per[c['expected_intent'] or 'guard'][a['category']]+=1
summary={'total':200,'categories':dict(counts),'per_intent':{k:dict(v) for k,v in per.items()},'actual_ok_ids':[c['id'] for c in base if c['actual']['status']=='ok'],'assessment_method':'manual query/expectation/response/status/slot/data/candidate review for every ID; no mechanical intent-only grading','source_limit_with_secondary_issue_ids':[a['id'] for a in A if a['category']=='safe_limitation' and ('secondary_' in a['issue_type'] or 'before_missing' in a['issue_type'])]}
(P/'assessment_counts.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(summary,ensure_ascii=False,indent=2))
