#!/usr/bin/env python3
"""Builds the independent gold acceptance evaluation test suite.

Contains 149 hand-crafted, manually reviewed test cases (>=21 per intent)
across formal Hindi, colloquial Hindi, Roman Hindi (Hinglish), code-mixed,
and typo variations.

Output: data/eval/acceptance_test_suite.json
"""

import json
import os
from typing import List, Dict, Any

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(BASE_DIR, "data", "eval", "acceptance_test_suite.json")

CASES: List[Dict[str, Any]] = [
    # =========================================================================
    # INTENT 1: route_query (22 cases)
    # =========================================================================
    {
        "id": "acc_route_001",
        "query": "चेन्नई सेंट्रल से एयरपोर्ट कैसे जाऊँ?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["चेन्नई सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": ["₹", "किराया ₹", "मिनट"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_002",
        "query": "सेंट्रल से एयरपोर्ट जाने का रास्ता बताइए",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": ["₹", "किराया"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_003",
        "query": "central se airport kaise jaye",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_route_004",
        "query": "central to airport route",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_route_005",
        "query": "एयरपोर्ट सेंट्रल से कैसे जाऊँ?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "reversed_wording"
    },
    {
        "id": "acc_route_006",
        "query": "airport central se kaise jau",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "reversed_wording"
    },
    {
        "id": "acc_route_007",
        "query": "सेंट्रल से एग्मोर जाने के लिए मेट्रो का क्या मार्ग है?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_EGMORE",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_008",
        "query": "एग्मोर से कोयम्बेडु कैसे पहुंचें?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_EGMORE",
        "gold_destination": "KOYAMBEDU",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["एग्मोर", "कोयम्बेडु"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_009",
        "query": "कोयम्बेडु से एयरपोर्ट कैसे जाएं?",
        "gold_intent": "route_query",
        "gold_origin": "KOYAMBEDU",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_transfer",
        "expected_substrings": ["कोयम्बेडु", "एयरपोर्ट", "बदलना"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_route_010",
        "query": "koyambedu se airport kaise jaye",
        "gold_intent": "route_query",
        "gold_origin": "KOYAMBEDU",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_transfer",
        "expected_substrings": ["कोयम्बेडु", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_route_011",
        "query": "सीएमबीटी से एयरपोर्ट जाने का रास्ता क्या है?",
        "gold_intent": "route_query",
        "gold_origin": "CMBT",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_transfer",
        "expected_substrings": ["सीएमबीटी", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_012",
        "query": "गिंडी से सेंट्रल कैसे जाएं?",
        "gold_intent": "route_query",
        "gold_origin": "GUINDY",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["गिंडी", "सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_route_013",
        "query": "वडापलानी से आलंदूर जाने का रूट",
        "gold_intent": "route_query",
        "gold_origin": "VADAPALANI",
        "gold_destination": "ALANDUR",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["वडापलानी", "आलंदूर"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_route_014",
        "query": "नंदनम से एयरपोर्ट कैसे पहुंचें?",
        "gold_intent": "route_query",
        "gold_origin": "NANDANAM",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["नंदनम", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_route_015",
        "query": "एयरपोर्ट कैसे जाऊँ?",
        "gold_intent": "route_query",
        "gold_origin": None,
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_origin",
        "expected_substrings": ["कहाँ से", "आरंभिक"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_route_016",
        "query": "सेंट्रल से कहाँ जाऊँ?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_destination",
        "expected_substrings": ["कहाँ जाना", "गंतव्य"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_route_017",
        "query": "airport kaise jau?",
        "gold_intent": "route_query",
        "gold_origin": None,
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_origin",
        "expected_substrings": ["कहाँ से"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_route_018",
        "query": "सेंट्रल से दिल्ली कैसे जाएं?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "unknown_station",
        "expected_substrings": ["गंतव्य"],
        "forbidden_substrings": [],
        "linguistic_form": "unknown_endpoint"
    },
    {
        "id": "acc_route_019",
        "query": "सेंट्रल से एयरपोट कैसे जाएं",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "typo"
    },
    {
        "id": "acc_route_020",
        "query": "chenai sentral to airport route",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "typo"
    },
    {
        "id": "acc_route_021",
        "query": "मुझे सेंट्रल से एग्मोर जाना है, रास्ता क्या है?",
        "gold_intent": "route_query",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_EGMORE",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["सेंट्रल", "एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_route_022",
        "query": "शेनॉय नगर से सेंट्रल जाने के लिए कौन सी ट्रेन लूं?",
        "gold_intent": "route_query",
        "gold_origin": "SHENOY_NAGAR",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": None,
        "expected_response_type": "route_direct",
        "expected_substrings": ["शेनॉय नगर", "सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },

    # =========================================================================
    # INTENT 2: service_availability (21 cases)
    # =========================================================================
    {
        "id": "acc_avail_001",
        "query": "सेंट्रल से गिंडी के लिए मेट्रो है क्या?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "GUINDY",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "गिंडी", "मेट्रो"],
        "forbidden_substrings": ["उपलब्ध नहीं"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_002",
        "query": "क्या चेन्नई सेंट्रल से एयरपोर्ट के लिए सीधी मेट्रो सेवा उपलब्ध है?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "चेन्नई सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_003",
        "query": "central se airport ke liye metro available hai kya?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_avail_004",
        "query": "airport ke liye central se direct metro hai kya?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ"],
        "forbidden_substrings": [],
        "linguistic_form": "reversed_wording"
    },
    {
        "id": "acc_avail_005",
        "query": "एग्मोर से एयरपोर्ट जाने के लिए सीधी मेट्रो मिलेगी?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_EGMORE",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_transfer",
        "expected_substrings": ["एग्मोर", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_avail_006",
        "query": "क्या सेंट्रल से एग्मोर के बीच मेट्रो चलती है?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_EGMORE",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_007",
        "query": "सेंट्रल से कोयम्बेडु के लिए मेट्रो कनेक्टिविटी है?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "KOYAMBEDU",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "कोयम्बेडु"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_008",
        "query": "koyambedu se airport metro connectivity hai kya?",
        "gold_intent": "service_availability",
        "gold_origin": "KOYAMBEDU",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_transfer",
        "expected_substrings": ["कोयम्बेडु", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_avail_009",
        "query": "सीएमबीटी से सेंट्रल मेट्रो मिलेगी क्या?",
        "gold_intent": "service_availability",
        "gold_origin": "CMBT",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सीएमबीटी", "सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_avail_010",
        "query": "क्या विमको नगर से सेंट्रल जाने के लिए मेट्रो उपलब्ध है?",
        "gold_intent": "service_availability",
        "gold_origin": "WIMCO_NAGAR",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "विमको नगर", "सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_011",
        "query": "वाशरमैनपेट से सेंट्रल के लिए मेट्रो सेवा चालू है क्या?",
        "gold_intent": "service_availability",
        "gold_origin": "WASHERMANPET",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "वाशरमैनपेट", "सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_012",
        "query": "सेंट्रल से गिंडी बस मिलेगी কি?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "GUINDY",
        "gold_station": None,
        "gold_mode": "bus",
        "gold_facility": None,
        "expected_response_type": "unknown_connectivity",
        "expected_substrings": ["सेंट्रल", "गिंडी"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_avail_013",
        "query": "central se guindy metro milegi kya",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "GUINDY",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "गिंडी"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_avail_014",
        "query": "centrl se airport metro available hai?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "typo"
    },
    {
        "id": "acc_avail_015",
        "query": "सेंट्रल से वडापलानी डायरेक्ट मेट्रो है क्या?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "VADAPALANI",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "unknown_connectivity",
        "expected_substrings": ["सेंट्रल", "वडापलानी"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_avail_016",
        "query": "क्या एयरपोर्ट के लिए मेट्रो उपलब्ध है?",
        "gold_intent": "service_availability",
        "gold_origin": None,
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "missing_origin",
        "expected_substrings": ["कहाँ से"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_avail_017",
        "query": "सेंट्रल से मेट्रो उपलब्ध है কি?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "missing_destination",
        "expected_substrings": ["कहाँ जाना"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_avail_018",
        "query": "airport metro available?",
        "gold_intent": "service_availability",
        "gold_origin": None,
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "missing_origin",
        "expected_substrings": ["कहाँ से"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_avail_019",
        "query": "सेंट्रल से किसी अज्ञात जगह के लिए मेट्रो है?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "missing_destination",
        "expected_substrings": ["कहाँ जाना"],
        "forbidden_substrings": [],
        "linguistic_form": "unknown_endpoint"
    },
    {
        "id": "acc_avail_020",
        "query": "सेंट्रल से सेंट थॉमस माउंट के लिए ग्रीन लाइन मेट्रो है?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "ST_THOMAS_MOUNT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "सेंट थॉमस माउंट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_avail_021",
        "query": "kya central se egmore metro chal rahi hai?",
        "gold_intent": "service_availability",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_EGMORE",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "service_available_yes",
        "expected_substrings": ["हाँ", "सेंट्रल", "एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },

    # =========================================================================
    # INTENT 3: service_timing (21 cases)
    # =========================================================================
    {
        "id": "acc_time_001",
        "query": "आखिरी मेट्रो कब छूटती है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["05:00", "23:00", "11:00"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_002",
        "query": "चेन्नई सेंट्रल से पहली मेट्रो कितने बजे है?",
        "gold_intent": "service_timing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["05:00", "04:30"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_003",
        "query": "रात को लास्ट मेट्रो का टाइम क्या है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["23:00"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_004",
        "query": "last metro timing kya hai?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["23:00"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_005",
        "query": "central se first metro kab nikalti hai?",
        "gold_intent": "service_timing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["05:00"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_006",
        "query": "मेट्रो कितने बजे तक चलती है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["23:00"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_007",
        "query": "एयरपोर्ट स्टेशन से सुबह पहली ट्रेन कब शुरू होती है?",
        "gold_intent": "service_timing",
        "gold_origin": "CHENNAI_AIRPORT",
        "gold_destination": None,
        "gold_station": "CHENNAI_AIRPORT",
        "gold_mode": "railway",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["05:00"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_008",
        "query": "metro operating hours kya hai?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_009",
        "query": "मेट्रो कितनी-कितनी देर में आती है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": ["6 मिनट", "12 मिनट"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_010",
        "query": "रविवार को मेट्रो का समय क्या रहता है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_011",
        "query": "कोयम्बेडु से पहली बस कब मिलेगी?",
        "gold_intent": "service_timing",
        "gold_origin": "KOYAMBEDU",
        "gold_destination": None,
        "gold_station": "KOYAMBEDU",
        "gold_mode": "bus",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_012",
        "query": "aakhiri train kitne baje hai?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_013",
        "query": "subah pehli metro timing from egmore",
        "gold_intent": "service_timing",
        "gold_origin": "CHENNAI_EGMORE",
        "gold_destination": None,
        "gold_station": "CHENNAI_EGMORE",
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_014",
        "query": "मेट्रो की फ्रिक्वेंसी कितनी है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_015",
        "query": "सेंट थॉमस माउंट से आखिरी मेट्रो कितने बजे रवाना होती है?",
        "gold_intent": "service_timing",
        "gold_origin": "ST_THOMAS_MOUNT",
        "gold_destination": None,
        "gold_station": "ST_THOMAS_MOUNT",
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_016",
        "query": "शाम के समय ट्रेनों का टाइम क्या है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_017",
        "query": "last metro ka time batao",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_018",
        "query": "आलंदूर से पहली ट्रेन कब है?",
        "gold_intent": "service_timing",
        "gold_origin": "ALANDUR",
        "gold_destination": None,
        "gold_station": "ALANDUR",
        "gold_mode": "railway",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_time_019",
        "query": "विमको नगर से पहली मेट्रो कितने बजे छूटती है?",
        "gold_intent": "service_timing",
        "gold_origin": "WIMCO_NAGAR",
        "gold_destination": None,
        "gold_station": "WIMCO_NAGAR",
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_time_020",
        "query": "pehli train kitne baje aati hai",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_time_021",
        "query": "रात्री के समय मेट्रो का संचालन कब तक होता है?",
        "gold_intent": "service_timing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "timing",
        "expected_response_type": "unsupported_timing",
        "expected_substrings": ["समय-सारणी", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },

    # =========================================================================
    # INTENT 4: station_information (21 cases)
    # =========================================================================
    {
        "id": "acc_station_001",
        "query": "चेन्नई सेंट्रल स्टेशन पर क्या सुविधाएं हैं?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["चेन्नई सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_002",
        "query": "एग्मोर स्टेशन की जानकारी दीजिए",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_EGMORE",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_003",
        "query": "alandur interchange station hai kya?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "ALANDUR",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["आलंदूर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_004",
        "query": "क्या आलंदूर एक इंटरचेंज स्टेशन है?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "ALANDUR",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["आलंदूर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_005",
        "query": "koyambedu station details kya hai?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "KOYAMBEDU",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["कोयम्बेडु"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_006",
        "query": "सीएमबीटी स्टेशन की जानकारी बताएं",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CMBT",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["सीएमबीटी"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_station_007",
        "query": "एयरपोर्ट मेट्रो स्टेशन के बारे में बताइए",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_AIRPORT",
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["एयरपोर्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_008",
        "query": "गिंडी स्टेशन किस लाइन पर है?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "GUINDY",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["गिंडी"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_station_009",
        "query": "वडापलानी स्टेशन पर कौन सी लाइन जुड़ती है?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "VADAPALANI",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["वडापलानी"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_010",
        "query": "नंदनम स्टेशन के पास कौन सा मुख्य क्षेत्र है?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "NANDANAM",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["नंदनम"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_011",
        "query": "सेंट्रल स्टेशन पर कौन सी लाइनें मिलती हैं?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_station_012",
        "query": "शेनॉय नगर स्टेशन की सुविधाएं",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "SHENOY_NAGAR",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["शेनॉय नगर"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_station_013",
        "query": "wimco nagar station kis line par hai",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "WIMCO_NAGAR",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["विमको नगर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_014",
        "query": "सेंट थॉमस माउंट मेट्रो स्टेशन विवरण",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "ST_THOMAS_MOUNT",
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["सेंट थॉमस माउंट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_015",
        "query": "स्टेशन पर क्या सुविधाएं हैं?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_station",
        "expected_substrings": ["स्टेशन का नाम"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_station_016",
        "query": "station facilities details?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_station",
        "expected_substrings": ["स्टेशन का नाम"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_017",
        "query": "किसी अनजान स्टेशन की जानकारी दो",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "missing_station",
        "expected_substrings": ["स्टेशन का नाम"],
        "forbidden_substrings": [],
        "linguistic_form": "unknown_endpoint"
    },
    {
        "id": "acc_station_018",
        "query": "वाशरमैनपेट मेट्रो स्टेशन का जंक्शन",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "WASHERMANPET",
        "gold_mode": "metro",
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["वाशरमैनपेट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_station_019",
        "query": "egmore station amenities",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_EGMORE",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_020",
        "query": "guindy station interchange options kya hai?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "GUINDY",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["गिंडी"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_station_021",
        "query": "सेंट्रल स्टेशन किस प्रकार का जंक्शन है?",
        "gold_intent": "station_information",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "station_identity",
        "expected_substrings": ["सेंट्रल"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },

    # =========================================================================
    # INTENT 5: accessibility (21 cases)
    # =========================================================================
    {
        "id": "acc_access_001",
        "query": "कोयम्बेडु स्टेशन पर व्हीलचेयर उपलब्ध है क्या?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "KOYAMBEDU",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "कोयम्बेडु", "व्हीलचेयर"],
        "forbidden_substrings": ["उपलब्ध नहीं"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_002",
        "query": "क्या चेन्नई सेंट्रल स्टेशन पर लिफ्ट है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "चेन्नई सेंट्रल", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_003",
        "query": "koyambedu par wheelchair available hai kya?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "KOYAMBEDU",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "कोयम्बेडु", "व्हीलचेयर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_access_004",
        "query": "central metro station par lift facility hai?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": "metro",
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "सेंट्रल", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_access_005",
        "query": "एग्मोर पर दिव्यांगों के लिए क्या सुविधा है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_EGMORE",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["एग्मोर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_006",
        "query": "एयरपोर्ट स्टेशन पर व्हीलचेयर सहायता मिलेगी क्या?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_AIRPORT",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "एयरपोर्ट", "व्हीलचेयर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_007",
        "query": "क्या गिंडी स्टेशन पर लिफ्ट की सुविधा है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "GUINDY",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "गिंडी", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_008",
        "query": "सीएमबीटी मेट्रो स्टेशन पर रैंप और लिफ्ट है کیا?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CMBT",
        "gold_mode": "metro",
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "सीएमबीटी", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_access_009",
        "query": "सेंट्रल पर दृष्टिबाधितों के लिए स्पर्श पथ (tactile path) है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": "tactile_paths",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "सेंट्रल", "स्पर्श पथ"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_010",
        "query": "kya airport station wheelchair accessible hai?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_AIRPORT",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "एयरपोर्ट", "व्हीलचेयर"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_access_011",
        "query": "आलंदूर स्टेशन पर एस्केलेटर और लिफ्ट काम कर रहे हैं क्या?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "ALANDUR",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "आलंदूर"],
        "forbidden_substrings": ["काम कर रहे हैं", "चालू हैं"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_access_012",
        "query": "वडापलानी स्टेशन पर व्हीलचेयर मिलेगी?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "VADAPALANI",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "वडापलानी", "व्हीलचेयर"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_access_013",
        "query": "शेनॉय नगर में लिफ्ट है کیا?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "SHENOY_NAGAR",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "शेनॉय नगर", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_access_014",
        "query": "नंदनम मेट्रो स्टेशन पर दिव्यांग शौचालय है کیا?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "NANDANAM",
        "gold_mode": "metro",
        "gold_facility": "accessible_toilet",
        "expected_response_type": "facility_available",
        "expected_substrings": ["नंदनम"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_015",
        "query": "क्या स्टेशन पर व्हीलचेयर मिलेगी?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "missing_station",
        "expected_substrings": ["स्टेशन का नाम"],
        "forbidden_substrings": [],
        "linguistic_form": "missing_slot"
    },
    {
        "id": "acc_access_016",
        "query": "wheelchair milegi kya?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "missing_station",
        "expected_substrings": ["स्टेशन का नाम"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_access_017",
        "query": "सेंट थॉमस माउंट पर स्पर्श पथ (tactile path) है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "ST_THOMAS_MOUNT",
        "gold_mode": None,
        "gold_facility": "tactile_paths",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "सेंट थॉमस माउंट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_018",
        "query": "वाशरमैनपेट स्टेशन पर लिफ्ट है क्या?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "WASHERMANPET",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "वाशरमैनपेट", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_019",
        "query": "विमको नगर स्टेशन पर रैंप सुविधा है?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "WIMCO_NAGAR",
        "gold_mode": None,
        "gold_facility": "ramp",
        "expected_response_type": "facility_unknown",
        "expected_substrings": ["विमको नगर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_access_020",
        "query": "egmore par lift available hai kya?",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_EGMORE",
        "gold_mode": None,
        "gold_facility": "lift",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "एग्मोर", "लिफ्ट"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_access_021",
        "query": "सेंट्रल स्टेशन पर व्हीलचेयर और स्ट्रेचर सहायता",
        "gold_intent": "accessibility",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_CENTRAL",
        "gold_mode": None,
        "gold_facility": "wheelchair",
        "expected_response_type": "facility_available",
        "expected_substrings": ["हाँ", "सेंट्रल", "व्हीलचेयर"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },

    # =========================================================================
    # INTENT 6: ticketing (21 cases)
    # =========================================================================
    {
        "id": "acc_ticket_001",
        "query": "चेन्नई सेंट्रल से एयरपोर्ट का मेट्रो किराया कितना है?",
        "gold_intent": "ticketing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹40", "₹50", "₹10", "40 रुपये"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_002",
        "query": "सेंट्रल से एयरपोर्ट का टिकट कितने का है?",
        "gold_intent": "ticketing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_003",
        "query": "central to airport ticket price kya hai?",
        "gold_intent": "ticketing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_004",
        "query": "central se egmore ka metro fare kitna hai?",
        "gold_intent": "ticketing",
        "gold_origin": "CHENNAI_CENTRAL",
        "gold_destination": "CHENNAI_EGMORE",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹10", "₹20"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_005",
        "query": "मेट्रो का न्यूनतम और अधिकतम किराया क्या है?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹10 से ₹50", "₹10 से ₹60"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_006",
        "query": "metro card recharge kaise kare?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": ["20% छूट"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_007",
        "query": "क्या मेट्रो में व्हाट्सएप से टिकट ले सकते हैं?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["टिकट", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_008",
        "query": "क्यूआर कोड से टिकट कैसे खरीदें?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["टिकट", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_009",
        "query": "वरिष्ठ नागरिकों के लिए टिकट में छूट है क्या?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_010",
        "query": "स्मार्ट कार्ड से यात्रा करने पर कितना डिस्काउंट मिलता है?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": ["20% छूट"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_011",
        "query": "koyambedu to airport metro ticket kitne ka hai?",
        "gold_intent": "ticketing",
        "gold_origin": "KOYAMBEDU",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_012",
        "query": "किराया कितना लगेगा?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_013",
        "query": "ticket counter kahan par hai?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["टिकट", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_014",
        "query": "मासिक पास कैसे बनवाएं?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_015",
        "query": "बच्चों के लिए टिकट का नियम क्या है?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_016",
        "query": "एनसीएमसी कार्ड मेट्रो में चलेगा क्या?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["नियम", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_017",
        "query": "ticket price from egmore to central",
        "gold_intent": "ticketing",
        "gold_origin": "CHENNAI_EGMORE",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_018",
        "query": "टोकन कहाँ से मिलेगा?",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["टिकट", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_ticket_019",
        "query": "आलंदूर से सेंट्रल का किराया कितना है?",
        "gold_intent": "ticketing",
        "gold_origin": "ALANDUR",
        "gold_destination": "CHENNAI_CENTRAL",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_ticket_020",
        "query": "metro ka kiraya kitna lagta hai",
        "gold_intent": "ticketing",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "metro",
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_ticket_021",
        "query": "वडापलानी से एयरपोर्ट का किराया क्या है?",
        "gold_intent": "ticketing",
        "gold_origin": "VADAPALANI",
        "gold_destination": "CHENNAI_AIRPORT",
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": "fare",
        "expected_response_type": "unsupported_fare",
        "expected_substrings": ["किराया", "उपलब्ध नहीं"],
        "forbidden_substrings": ["₹"],
        "linguistic_form": "formal_hi"
    },

    # =========================================================================
    # INTENT 7: out_of_scope (22 cases)
    # =========================================================================
    {
        "id": "acc_oos_001",
        "query": "आज चेन्नई में मौसम कैसा है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": ["मौसम", "धूप", "बारिश"],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_oos_002",
        "query": "aaj chennai ka weather kaisa hai?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_003",
        "query": "मेरी ट्रेन अभी कितनी लेट चल रही है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": None,
        "expected_response_type": "unsupported_live_status",
        "expected_substrings": ["लाइव", "उपलब्ध नहीं"],
        "forbidden_substrings": ["10 मिनट लेट"],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_004",
        "query": "meri train kitni late hai",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": None,
        "expected_response_type": "unsupported_live_status",
        "expected_substrings": ["लाइव", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_005",
        "query": "चेन्नई में घूमने की अच्छी जगहें कौन सी हैं?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_oos_006",
        "query": "chennai me best places to visit?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_007",
        "query": "पास का कोई अच्छा रेस्टोरेंट बताइए",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_008",
        "query": "सीएसके का अगला मैच कब है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_009",
        "query": "भारत का प्रधानमंत्री कौन है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_oos_010",
        "query": "मुझे एक अच्छा चुटकुला सुनाइए",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_011",
        "query": "tell me a joke",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_012",
        "query": "टैक्सी बुक करने का कोई नंबर बताइए",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_013",
        "query": "कल की ट्रेन का पीएनआर स्टेटस चेक कर दो",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "railway",
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_014",
        "query": "cricket score kya chal raha hai?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_015",
        "query": "होटल बुक करने का सुझाव दें",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_oos_016",
        "query": "एयरपोर्ट पर फ्लाइट लेट है क्या?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": "CHENNAI_AIRPORT",
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "unsupported_live_status",
        "expected_substrings": ["लाइव", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_017",
        "query": "flight status check karo",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_018",
        "query": "चेन्नई में सबसे अच्छा सिनेमा हॉल कौन सा है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_019",
        "query": "tum kaun ho?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    },
    {
        "id": "acc_oos_020",
        "query": "आप क्या-क्या कर सकते हैं?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "formal_hi"
    },
    {
        "id": "acc_oos_021",
        "query": "मेरी बस अभी कहाँ पहुँची है?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": "bus",
        "gold_facility": None,
        "expected_response_type": "unsupported_live_status",
        "expected_substrings": ["लाइव", "उपलब्ध नहीं"],
        "forbidden_substrings": [],
        "linguistic_form": "colloquial_hi"
    },
    {
        "id": "acc_oos_022",
        "query": "chennai me aaj barish hogi kya?",
        "gold_intent": "out_of_scope",
        "gold_origin": None,
        "gold_destination": None,
        "gold_station": None,
        "gold_mode": None,
        "gold_facility": None,
        "expected_response_type": "out_of_scope",
        "expected_substrings": ["सार्वजनिक परिवहन"],
        "forbidden_substrings": [],
        "linguistic_form": "hinglish"
    }
]


def save_acceptance_suite():
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(CASES, f, ensure_ascii=False, indent=2)

    # Verification counts
    intents: Dict[str, int] = {}
    forms: Dict[str, int] = {}
    for c in CASES:
        intents[c["gold_intent"]] = intents.get(c["gold_intent"], 0) + 1
        forms[c["linguistic_form"]] = forms.get(c["linguistic_form"], 0) + 1

    print(f"✅ Successfully wrote {len(CASES)} independent acceptance cases to: {OUTPUT_PATH}")
    print("\nCounts per intent:")
    for intent, count in sorted(intents.items()):
        print(f"  • {intent:25}: {count}")

    print("\nCounts per linguistic form:")
    for form, count in sorted(forms.items()):
        print(f"  • {form:25}: {count}")


if __name__ == "__main__":
    save_acceptance_suite()
